export const APP_NAME = 'Collaborative Team Hub';

export const ROLES = {
  ADMIN: 'ADMIN',
  MANAGER: 'MANAGER',
  MEMBER: 'MEMBER',
};

export const PERMISSIONS = {
  WORKSPACE_VIEW: 'workspace:view',
  GOALS_CREATE: 'goals:create',
  GOALS_DELETE: 'goals:delete',
  ANNOUNCEMENTS_CREATE: 'announcements:create',
  ANNOUNCEMENTS_PIN: 'announcements:pin',
  MEMBERS_INVITE: 'members:invite',
  MEMBERS_MANAGE_ROLES: 'members:manageRoles',
  REACTIONS_CREATE: 'reactions:create',
  COMMENTS_CREATE: 'comments:create',
  ANALYTICS_VIEW: 'analytics:view',
  ACTION_ITEMS_CREATE: 'actionItems:create',
  ACTION_ITEMS_DELETE: 'actionItems:delete',
};

export const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: [
    PERMISSIONS.WORKSPACE_VIEW,
    PERMISSIONS.GOALS_CREATE,
    PERMISSIONS.GOALS_DELETE,
    PERMISSIONS.ANNOUNCEMENTS_CREATE,
    PERMISSIONS.ANNOUNCEMENTS_PIN,
    PERMISSIONS.MEMBERS_INVITE,
    PERMISSIONS.MEMBERS_MANAGE_ROLES,
    PERMISSIONS.REACTIONS_CREATE,
    PERMISSIONS.COMMENTS_CREATE,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ACTION_ITEMS_CREATE,
    PERMISSIONS.ACTION_ITEMS_DELETE,
  ],
  [ROLES.MANAGER]: [
    PERMISSIONS.WORKSPACE_VIEW,
    PERMISSIONS.GOALS_CREATE,
    PERMISSIONS.GOALS_DELETE,
    PERMISSIONS.ANNOUNCEMENTS_CREATE,
    PERMISSIONS.ANNOUNCEMENTS_PIN,
    PERMISSIONS.MEMBERS_INVITE,
    PERMISSIONS.REACTIONS_CREATE,
    PERMISSIONS.COMMENTS_CREATE,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ACTION_ITEMS_CREATE,
    PERMISSIONS.ACTION_ITEMS_DELETE,
  ],
  [ROLES.MEMBER]: [
    PERMISSIONS.WORKSPACE_VIEW,
    PERMISSIONS.GOALS_CREATE,
    PERMISSIONS.REACTIONS_CREATE,
    PERMISSIONS.COMMENTS_CREATE,
    PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.ACTION_ITEMS_CREATE,
  ],
};
